services:
  dev_postgres:
    image: postgres:latest
    container_name: damaru-dev
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db/pgData:/var/lib/postgresql/data
volumes:
  pgData: