export enum Actions {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  CREATE_EMULATOR = 'CREATE_EMULATOR',
  UPDATE_EMULATOR = 'UPDATE_EMULATOR',
  DELETE_EMULATOR = 'DELETE_EMULATOR',
  LINK_EMULATOR = 'LINK_EMULATOR',
  START_STREAMING = 'START_STREAMING',
}
