version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
            - npm-deps-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: npm-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Build app
          command: npm run build

      - run:
          name: Zip build
          command: zip -r dist.zip dist package.json package-lock.json node_modules

      - persist_to_workspace:
          root: .
          paths:
            - dist.zip

  deploy_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: Setup SSH Key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - run:
          name: Transfer to Server
          command: scp -i ~/.ssh/id_rsa dist.zip $SSH_USER@$SERVER_IP:/home/ubuntu/damaru-dev

      - run:
          name: Deploy on Test Server
          command: ssh -i ~/.ssh/id_rsa $SSH_USER@$SERVER_IP "sh /home/ubuntu/damaru-dev/deploy-dev.sh"

  deploy_live:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: Setup SSH Key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - run:
          name: Transfer to Server
          command: scp -i ~/.ssh/id_rsa dist.zip $SSH_USER@$SERVER_IP:/home/ubuntu/damaru

      - run:
          name: SSH to server and deploy (Live)
          command: ssh -i ~/.ssh/id_rsa $SSH_USER@$SERVER_IP "sh /home/ubuntu/damaru/deploy-live.sh"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy_test:
          requires:
            - build
          filters:
            branches:
              only:
                - test
      - deploy_live:
          requires:
            - build
          filters:
            branches:
              only:
                - live
